### ISSUE TITLE
Name in Linux deployable has a typo

### ISSUE THREAD

**Issue by sachinlala** [andreas-schroeder/kafka-health-check#10]
Hi @andreas-schroeder, I have just started testing the utility to health-check a multi-node Kafka cluster setup (based on HashiCorp stack) and it's looking good so far.
One minor observation - the name of binary in the Linux deployable (kafka-health-check_0.0.0_linux_amd64.tar.gz) is 'kafha-health-check' instead of 'kafka-health-check'. Please could you correct this or let me know if I can.
Also is it not time now to call the version 1.0.0 ?
Cheers.

**Comment by andreas-schroeder** [comment]
Hi @sachinlala,

thanks for pointing that out, I also noticed that a few days ago and fixed it in https://github.com/andreas-schroeder/kafka-health-check/releases/tag/v0.0.1

About the versioning, I prefer starting with 0 (like array indices) and follow semantic versioning conventions.

I'll close this issue, feel free to reopen it if v0.0.1 doesn't work out for you.

**Comment by sachinlala** [comment]
Thanks @andreas-schroeder. This checks out good. Happy to see the latest release as v0.0.1.
