### ISSUE TITLE
Add option for min.insync.replicas

### ISSUE THREAD

**Issue by Luzifer** [andreas-schroeder/kafka-health-check#11]
## Observation

In our production environment the `min.insync.replicas` setting is set to `2` for stability reasons. As the `kafka_health_check` is creating its non-replicating topics with a `replication-factor` of `1` this makes the cluster check fail because Kafka is not accepting writes to those topics.

## Expectation

The topic is replicated to ensure the `min.insync.replicas` expectation is fulfilled and then checked.

**Comment by Luzifer** [comment]
cc @imusmanmalik

**Comment by andreas-schroeder** [comment]
Hi @Luzifer, 

interesting point. The approach of this tool is to check [replication of partitions](https://github.com/andreas-schroeder/kafka-health-check/blob/master/check/broker_health_check.go#L78) and [basic record replay](https://github.com/andreas-schroeder/kafka-health-check/blob/master/check/broker_health_check.go#L18-L22) separately. It doesn't check that the ISR sizes are satisfying a desired `min.insyc.replicas` size.

How I suggest to proceed:
_Reproducing and fixing the immediate issue:_ If this issue can be reproduced, I would configure the replication check topics [on creation](https://github.com/andreas-schroeder/kafka-health-check/blob/master/check/setup.go#L172-L173) with `min.insyc.replicas` of 1 and override the cluster's defaults (in your case of 2). This fix I would track in a followup issue with a title that states this bug properly.

_Enhancement to check for ISR size versus min.insync.replicas:_ If you need this, please open a separate issue. This would involve some work to do, as a cluster can have a default `min.insync.replicas`, and some topics may have overrides for `min.insync.replicas`. These scenarios need to be considered. If you feel like contributing this enhancement, PR's are very welcome :)

**Comment by Luzifer** [comment]
I think for our use case (checking whether the broker is alive and working) the first solution (overriding the configuration for the specific topic) sounds good. In the end the data inside that topic is not that important we do need two copies of it no matter what and the replication is checked with the replication topic…

So for me the override would fix this issue! :)

**Comment by andreas-schroeder** [comment]
check out https://github.com/andreas-schroeder/kafka-health-check/releases/tag/v0.0.2
