### ISSUE TITLE
Am I using this correctly?

### ISSUE THREAD

**Issue by andycockers** [andreas-schroeder/kafka-health-check#19]
Hi,

I'm using the precompiled binary on Linux, running on a local machine which is pointing at a remote server.

My cmd line looks like this (machine names obscured)

./kafka-health-check -broker-host kafka-host -broker-id 1 -zookeeper kafka-host:2181

When I run this, I get the following output...

time="2018-01-09T11:50:13Z" level=info msg="using topic broker-1-health-check for broker 1 health check" 
time="2018-01-09T11:50:13Z" level=info msg="using topic broker-1-health-check for broker 1 replication check" 

I don't get any other output, and I'm not sure if that's correct or not. I'm not seeing any topics created in Kafka. If I query the health status on port 8000 I get

{"status": "nook"}

As far as I can tell, Kafka is working correctly, does anyone have any idea what's going on and is there any way I can diagnose it?

**Comment by josh-padnick** [comment]
I ran into this same behavior and you have to look at your Kafka logs to see what errors you see there. In my case, I had an `SSL` and `PLAINTEXT` listener defined in `listeners` property, but only one listener defined in my `advertised.listeners` property. Once I fixed this in all three Kafka brokers I started getting more output.

Admittedly, the program could do a better job of reporting the failure it receives in logs.

**Comment by andreas-schroeder** [comment]
Hi @josh-padnick , thanks for explaining, I've created issue #25 based in your input.
