### ISSUE TITLE
enable brokerHost variable for network environments where localhost will not work

### ISSUE THREAD

**Issue by hokiegeek2** [andreas-schroeder/kafka-health-check#4]
Hi Andreas,

First of all--great job on this! I've recently deployed it and it's working well.

My deployment network setup does not allow binding to localhost, so I needed to add a brokerHost variable. I forked the project and will submit a pull request today or over the weekend.

--John

**Comment by hokiegeek2** [comment]
Updated code and documentation, tested changes on my cluster, submitted pull request

**Comment by andreas-schroeder** [comment]
Pull Request merged, thanks a lot! :+1:

**Comment by hokiegeek2** [comment]
You got it Andreas! Thanks a lot for putting this kafka healthcheck together--well done!

--John
