### ISSUE TITLE
incorrect in-sync replica count for broker health check topic

### ISSUE THREAD

**Issue by hokiegeek2** [andreas-schroeder/kafka-health-check#6]
Getting the following error for the :
"producer failure - broker unhealthy: not enough in-sync replicas (19)"

However, kafka-topic.sh --describe shows that the topic has one in-sync replica, so this error condition is incorrect. I am digging into the code, but I am wondering if this is a zookeeper connection issue?

**Comment by andreas-schroeder** [comment]
Hello,

thanks for reporting the issue.

Producing doesn't need connection to ZooKeeper, so I would rule that out. 

The log output you are seeing to comes from [here](https://github.com/andreas-schroeder/kafka-health-check/blob/fb7ecb2d023d34d931dcbcd7a7216a5bb9a951ff/check/broker_health_check.go#L19), and the "not enough in-sync replicas" from [here](https://github.com/optiopay/kafka/blob/da83485a9782da40dae8eb440ad902472a36872f/proto/errors.go#L27) via [this line](https://github.com/optiopay/kafka/blob/da83485a9782da40dae8eb440ad902472a36872f/proto/errors.go#L85), meaning that the producer client got error code 19 back from the broker while trying to produce. Looking at [the specs](https://kafka.apache.org/protocol#protocol_error_codes), this seems to be the right error code.

So I'd suggest finding out why the broker reports error code 19 back? Maybe the check is too eager and tries to health check before the topic is properly set up?

By the way, which version of Kafka are you using?

**Comment by hokiegeek2** [comment]
Hi Andreas,

Good thought regarding topic setup race condition, but this error is being thrown for a previously-established Kafka topic.

Using Kafka 0.10.1.0 as of now. 

I added some print statements when I was looking at this a few days ago, and the error is coming from kafka-utils class. There must be a configurable variable that can be set to fix this. I've not revisited this in awhile as I have other, more pressing tasks, but hope to do so at some point.

**Comment by hokiegeek2** [comment]
Ah, I think I know that it is. There is one partition that has four replicas, the rest have three. This is not a bug in kafka-health-check or optiopay/kafka, just a weird edge case.

**Comment by andreas-schroeder** [comment]
Cool, glad that you found what caused your isse. 

Btw, I've extended the [compatibility checks](https://github.com/andreas-schroeder/kafka-health-check/blob/master/compatibility/spec.yaml) to also include 0.10.1.0, and [here are the results](https://travis-ci.org/andreas-schroeder/kafka-health-check/builds/263794089#L764) (spoiler alert: they pass :) ) 

I'll close this issue if that's okay - if you have any followup on this, reopen it & let me know :)

**Comment by hokiegeek2** [comment]
Yah, makes sense. Again, in any case, this is not a bug in this codebase.

**Comment by hokiegeek2** [comment]
And cool that the extended compatiblliry checks pass
