### ISSUE TITLE
SSL support: Does it connect to brokers configured with ssl

### ISSUE THREAD

**Issue by ltnilaysahu** [andreas-schroeder/kafka-health-check#9]

**Comment by andreas-schroeder** [comment]
Hi @ltnilaysahu,

currently it doesn't as it is primarily intended to be run on every broker locally (where you could  open an plaintext listener to the loopback network interface).

As this is more a question than an issue, I'll close this issue. If you have more questions concerning ssl, feel free to comment on this issue.
